@echo off
echo Forçando instalação completa das dependências...

echo 1. Removendo node_modules...
if exist node_modules rmdir /s /q node_modules

echo 2. Removendo package-lock.json...
if exist package-lock.json del package-lock.json

echo 3. Limpando cache do npm...
npm cache clean --force

echo 4. Instalando todas as dependências...
npm install --force

echo 5. Verificando instalação do CLI...
npm list @react-native-community/cli

echo.
echo ✅ Instalação completa! Tentando build...
echo.
npm run android 